# Generated by Django 3.1.7 on 2021-02-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alleknotentabelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knotenname_de', models.TextField()),
                ('knoten_frameweite', models.TextField()),
                ('knoten_framehoehe', models.TextField()),
                ('knoten_frame_2d', models.TextField()),
                ('knoten_frame_360', models.TextField()),
                ('knoten_count_x_2d', models.TextField()),
                ('knoten_count_y_2d', models.TextField()),
                ('knoten_count_x_360', models.TextField()),
                ('knoten_count_y_360', models.TextField()),
                ('knotenbild2d', models.TextField()),
                ('knotenbild360', models.TextField()),
                ('knoten_typ', models.TextField()),
                ('knotenname_eng', models.TextField()),
                ('knotenbeschreibung_de', models.TextField()),
                ('knoten_abok', models.TextField()),
                ('knotenwarnung_de', models.TextField()),
                ('knotenbeschreibung_eng', models.TextField()),
                ('knotenbeschreibung_esp', models.TextField()),
                ('knotenname_esp', models.TextField()),
                ('knotenbeschreibung_ru', models.TextField()),
                ('knotenname_ru', models.TextField()),
                ('knotenfestigkeit', models.TextField()),
                ('knotenname_fr', models.TextField()),
                ('knotenbeschreibung_fr', models.TextField()),
                ('knotenname_it', models.TextField()),
                ('knotenbeschreibung_it', models.TextField()),
                ('knotenname_tuek', models.TextField()),
                ('knotenbeschreibung_tuek', models.TextField()),
                ('knotenname_zh', models.TextField()),
                ('knotenbeschreibung_zh', models.TextField()),
                ('knotenname_ja', models.TextField()),
                ('knotenbeschreibung_ja', models.TextField()),
                ('knotenname_vi', models.TextField()),
                ('knotenbeschreibung_vi', models.TextField()),
                ('knotenname_pt', models.TextField()),
                ('knotenbeschreibung_pt', models.TextField()),
                ('knotenname_ko', models.TextField()),
                ('knotenbeschreibung_ko', models.TextField()),
            ],
            options={
                'verbose_name': 'Knot',
                'verbose_name_plural': 'Knots',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr', models.TextField()),
                ('knot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.alleknotentabelle')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorite',
            },
        ),
    ]
